@php
$model = [
    'name' => 'TLE-C190-CT-HD',
    'description' => '19.0" Industrial Touch Monitor',
    'category' => 'Industrial',
    'screen_size' => '19.0',
    'resolution' => '1280x1024',
    'brightness' => '250',
    'response_time' => '5ms',
    'image' => '/images/products/tle-c190-ct-hd.svg',
    'specifications' => [
        'Case/Frame Color' => 'Black',
        'Display Type' => 'Active matrix TFT LCD, LED backlight',
        'Diagonal Dimension' => '19.0" diagonal',
        'Aspect Ratio' => '5:4',
        'Active Area Dimensions' => '376.32mm(H) x 301.056mm(V)',
        'Display Size' => '430mm(W) x 355mm(H), Thickness: 47mm',
        'Resolution' => '1280 x 1024 @ 60Hz',
        'Display Colors' => '16.7M',
        'Brightness (Standard)' => '250 cd/m²',
        'Response Time (Standard)' => '5 ms',
        'View Angle (from center)' => 'L/R:85/85; U/D:80/80 (Typ.) (CR≥10)',
        'Contrast Ratio (Standard)' => '1000:1 (Typ.)',
        'Input Video Formats' => 'Analog VGA and digital DVI (optional HDMI, DP)',
        'Connector' => 'DE-15 VGA, DVI-D, Dual-Link, HDMI (female)',
        'Sweep Frequency' => 'Horizontal: 31.5–60.2 kHz; Vertical: 56.3–75 Hz',
        'Touch Technology' => 'Projected capacitive',
        'Touch Chip' => 'weida, eeti, ilitek',
        'Touch Points' => '1-10',
        'Touch Supply Voltage' => '5V',
        'Touch Interface' => 'USB',
        'Touch Support System' => 'Windows, Android, Linux',
        'Power' => 'External DC, input voltage DC: 12V (DC cartridge connector)',
        'Power Consumption (Standard)' => 'Display only: 13.5W (Typ.)',
        'Operating Temperature' => '0°C to 60°C',
        'Storage Temperature' => '-20°C to 60°C',
        'Operating Humidity' => '20% to 80% (no condensation)',
        'Storage Humidity' => '10% to 90% (non-condensing)',
        'MTBF' => '50,000 hours',
        'Weight (Approx.)' => 'Net 4.3 kg (Typ.); Shipping 5.8 kg (ref.)',
        'Warranty' => '1 year',
        'OSD' => 'Digital OSD',
        'User Controls' => 'Menu, Up, Down, Select, Power; OSD: Contrast, Brightness, H/V Bits Clock, Phase, Default, Language (EN/DE/ES/JA/FR)',
        'OSD Remote Accessories' => 'Optional front controls: Menu, Up, Down, Select, Power',
        'Mounting Options' => '100mm or 75mm VESA, open bracket mounting',
        'Water and Dust Protection' => 'IP65(front)/IK08(front)',
        'Surface Treatment' => 'AG / AR (optional)',
        'Agency Approvals' => 'UL, cUL (Recognized), FCC, CE, CB, China RoHS CQC',
    ],
    'related_products' => [
        ['name' => 'TLE-C170-CT-HD', 'description' => '17.0" Industrial Touch Monitor', 'screen_size' => '17.0', 'resolution' => '1280x1024', 'brightness' => '250', 'url' => '/products/industrial-et-17'],
        ['name' => 'TLE-C185B1000-CT-HD', 'description' => '18.5" Industrial Touch Monitor', 'screen_size' => '18.5', 'resolution' => '1920x1080', 'brightness' => '1000', 'url' => '/products/industrial-et-185'],
    ]
];
@endphp
@extends('pages.models.template')

