@php
$model = [
    'name' => 'TLE-L2762',
    'description' => '27" IP65 Open Frame PCAP Multitouch Touch Monitor',
    'category' => 'Industrial',
    'screen_size' => '27',
    'resolution' => '1920x1080',
    'brightness' => '300',
    'response_time' => '3ms',
    'image' => '/images/products/tle-l2762.svg',
    'specifications' => [
        'Model' => 'TLE-L2762',
        'Description' => '27" IP65 Open Frame PCAP Multitouch Touch Monitor',
        'Case/Bezel Color' => 'Steel/Black',
        'Display' => '27 inch Active matrix TFT LCD',
        'Aspect Ratio' => '16:9',
        'Optimal (native) Resolution' => '1920×1080 @60Hz',
        'Useful Screen Area' => '597.6mm × 336.2mm',
        'Brightness' => '300nits (500/1000/1500nits options)',
        'Contrast Ratio' => '3000:1 (Typical)',
        'I/O Ports' => 'USB Touch, VGA, DVI, HDMI, Audio In, Earphone Out, 12V DC in',
        'Viewing Angle (CR≥10)' => 'H: ±89° or 178° total; V: ±89° or 178° total',
        'Input Video Format' => 'VGA, DVI, HDMI Option',
        'Input Video Signal Connector' => 'VGA, DVI, HDMI Option',
        'On Screen Display' => 'Controls (back): on/off, Menu, Left, Right, Auto',
        'Backlight Lamp Life' => '50000 hrs',
        'Touch Technology' => 'Projected capacitive Touch Technology, True 10-40points Multitouch',
        'Response Time' => '3ms',
        'Touch Resolution' => '32767×32767',
        'Touch Glass' => '3mm Anti-vandal tempered glass meet IK07',
        'Seabillity' => 'Touchscreen sealed to Aluminum alloy-bezel IP65',
        'MTBF' => '50000 hrs demonstrated',
        'Touch Interface' => 'USB touch interface',
        'Support OS' => 'HID Mode: Windows 7/8/10/11, Linux, Android, Raspberry Pi, MAC, etc.',
        'Mounting Options' => 'VESA Mount (75mm or 100mm), Side Mount or Front Mount with optional bracket',
        'Power Supply' => '12V DC, (24V DC POE Option) External Adapter: 100-240VAC, 50-60Hz',
        'Temperature Range' => 'Operating: 0° C to 50° C; Storage: -20° C to 60° C',
        'Humidity Range (no condensing)' => 'Operating: 20%-80%; Storage: 10%-90%',
        'Dimension and Weight' => '656 × 393 × 53.5mm',
        'Warranty' => '1 year',
        'Agency Approvals' => 'CCC, FCC, CE, RoHS',
    ],
    'related_products' => [
        ['name' => 'TLE-L2382', 'description' => '23.8" IP65 Open Frame PCAP', 'screen_size' => '23.8', 'resolution' => '1920x1080', 'brightness' => '250', 'url' => '/products/tle-l2382'],
        ['name' => 'TLE-C215B1000-CT-HD', 'description' => '21.5" 1000 nits High Brightness', 'screen_size' => '21.5', 'resolution' => '1920x1080', 'brightness' => '1000', 'url' => '/products/tle-c215b1000-ct-hd'],
    ]
];
@endphp
@extends('pages.models.template')

