@php
$model = [
    'name' => 'TLE-C215-CT-HD',
    'description' => '21.5" Industrial Touch Monitor',
    'category' => 'Industrial',
    'screen_size' => '21.5',
    'resolution' => '1920x1080',
    'brightness' => '250',
    'response_time' => '14ms',
    'image' => '/images/products/tle-c215-ct-hd.svg',
    'specifications' => [
        'Case/Frame Color' => 'Black',
        'Display Type' => 'Active matrix TFT LCD, LED backlight',
        'Diagonal Dimension' => '21.5" diagonal',
        'Aspect Ratio' => '16:9',
        'Active Area Dimensions' => '479.6mm(H) x 270.9mm(V)',
        'Display Size' => '532.2mm(W) x 319.4mm(H), Thickness: 46.5mm',
        'Resolution' => '1920 x 1080 @ 60Hz',
        'Display Colors' => '16.7M',
        'Brightness (Standard)' => '250 cd/m²',
        'Response Time (Standard)' => '14 ms',
        'View Angle (from center)' => 'L/R:89/89; U/D:89/89 (Typ.) (CR≥10)',
        'Contrast Ratio (Standard)' => '3000:1 (Typ.)',
        'Input Video Formats' => 'Analog VGA and digital DVI, HDMI (DP optional)',
        'Sweep Frequency' => 'Horizontal: 31.5–60.2 kHz; Vertical: 56.3–75 Hz',
        'Touch Technology' => 'Projected capacitive',
        'Touch Chip' => 'weida, eeti, ilitek',
        'Touch Points' => '1-10',
        'Touch Supply Voltage' => '5V',
        'Touch Interface' => 'USB',
        'Touch Support System' => 'Windows, Android, Linux',
        'Power' => 'External DC 12V',
        'Power Consumption (Standard)' => 'Display only: 20W (Typ.)',
        'Operating Temperature' => '0°C ~ 50°C',
        'Storage Temperature' => '-20°C ~ 60°C',
        'Operating Humidity' => '20% to 80% (no condensation)',
        'Storage Humidity' => '10% to 90% (non-condensing)',
        'MTBF' => '50,000 hours',
        'Weight (Approx.)' => 'Net 5.8 kg (Typ.); Shipping 8 kg (ref.)',
        'Warranty' => '1 year',
        'OSD' => 'Digital OSD',
        'User Controls' => 'Menu, Up, Down, Select, Power',
        'Mounting Options' => '100mm or 75mm VESA mounting, open bracket mounting',
        'Water and Dust Protection' => 'IP65(front)/IK08(front)',
        'Surface Treatment' => 'AG / AR (optional)',
        'Agency Approvals' => 'FCC, CE, CB, China RoHS CQC',
    ],
    'related_products' => [
        ['name' => 'TLE-L2382', 'description' => '23.8" IP65 Open Frame PCAP', 'screen_size' => '23.8', 'resolution' => '1920x1080', 'brightness' => '250', 'url' => '/products/tle-l2382'],
        ['name' => 'TLE-L2762', 'description' => '27" IP65 Open Frame PCAP', 'screen_size' => '27', 'resolution' => '1920x1080', 'brightness' => '300', 'url' => '/products/tle-l2762'],
    ]
];
@endphp
@extends('pages.models.template')

